version: "3"

services:
  app:
    build: .
    volumes:
      - ..:/var/www/html

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: root
      POSTGRES_HOST_AUTH_METHOD: trust